name: conditionals
on:
  push:
  workflow_dispatch:
jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - name: A step that only runs when the branch is main
        if: ${{ github.ref_name == 'main' }}
        run: echo "running on main branch"

      - name: demo fail step
        run: exit 1

      - name: A step that only runs when the previous step failed
        if: ${{ failure() }}
        run: echo "previous step failed"
      
      - name: Step with continue-on-error
        continue-one-error: true
        run: |
          echo "This step will fail but workflow continues"
          exit 1
      - name: This still runs despite failure above
        run: echo "Workflow did not stop 👍"
  
  push-event-job:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push'}}
    steps:
      - name: A job that only runs on push events, not on pull requests
        run: echo "job is running as push event happened"
                                                                                 


