name: github-hosted-demo
on:
  workflow_dispatch:
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: print os info
        run: |
          echo "OS name:$(uname -s)"
          echo "Hostname: $(hostname)"
          echo "Username: $USER"
  windows:
    runs-on: windows-latest
    steps:
      - name: print os info
        #shell: bash
        shell: powershell
        run: |
          #echo "OS name:$(uname -s)"
          #echo "Hostname: $(hostname)"
          #echo "Username: $USER"
          Write-Output "OS name: $env:OS"
          Write-Output "Hostname: $env:COMPUTERNAME"
          Write-Output "Username: $env:USERNAME"
  mac:
    runs-on: macos-latest
    steps:
      - name: print os info
        shell: bash
        run: |
          echo "OS name:$(uname -s)"
          echo "Hostname: $(hostname)"
          echo "Username: $USER"
          
