name: hello
on:
  workflow_dispatch
  # push:
  # branches: [main]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: chekout code
        uses: actions/checkout@v4
      - name: print statement
        run: echo "Hello from GitHub Actions!"
      - name: Print the current date and time
        run: date
      - name: Print the name of the branch that triggered the run
        run: echo ${{ github.ref_name }}
      - name: List the files in the repo
        run: ls -la
      - name: Print the runner's operating system
        run: uname -s
