name: pre-check
on:
  workflow_dispatch:
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
        - name: version_print
          run: |
            docker --version
            git --version
            node --version
            python --version
