name: reusable-workflow
on:
 workflow_call:
  inputs:
    app_name:
     type: string
     required: true
    environment:
     type: string
     required: true
     default: staging
  secrets:
    docker_token:
     required: true
   
jobs:
 code:
  runs-on: ubuntu-latest
  steps:
    - name: checkout code
      uses: actions/checkout@v4
 print:
  runs-on: ubuntu-latest
  steps:
    - name: print app name with enviornment
      run: echo "Building ${{ inputs.app_name }} for ${{ inputs.environment }}"
 print2:
  runs-on: ubuntu-latest
  steps:
    - name: print secret set
      run: echo "Docker token is set':' true"
 
