name: secret-demo
on:
  workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: try to print secret
        run: |
          echo "The secret is set: true"
          echo "Secret Value: ${{ secrets.MY_SECRET_MESSAGE }}"
