name: secrets-as-env
on:
  workflow_dispatch
jobs:
  secret-var:
    runs-on: ubuntu-latest
    steps:
      - name: docker-login
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
        run: |
          echo "Login into docker"
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
