name: self-hosted-demo

on:
  workflow_dispatch:

jobs:
  self-demo:
    runs-on: [self-hosted, Linux, vishals-ec2-instance]

    steps:
      - uses: actions/checkout@v4

      - name: print hostname
        run: hostname

      - name: print working directory
        run: |
          echo "PWD: $(pwd)"
          ls -la

      - name: create file
        run: echo "demo file" > demo.txt

      - name: verify file exist
        run: |
          if [ -f demo.txt ]; then
            echo "file exist"
          else
            echo "file does not exist"
          fi

      - name: list files after creation
        run: ls -la
